export type Locale = 'de' | 'en';

export const content = {
  de: {
    locale: 'de-DE',
    path: '/',
    switchPath: '/en/',
    switchLabel: 'EN',
    metaTitle: 'Geschäftsprozesse digitalisieren | Treppmann Studio',
    metaDescription: 'Prozessoptimierung, Prozessautomatisierung und individuelle Software für komplexe Geschäftsabläufe. Interne Tools und AI-gestützte Workflows aus Berlin.',
    nav: { work: 'Arbeit', offer: 'Angebot', studio: 'Studio', contact: 'Kontakt' },
    hero: {
      kicker: 'Prozessoptimierung · Automatisierung · Individualsoftware',
      title: 'Komplexe Abläufe. Werkzeuge, die passen.',
      intro: 'Wir analysieren und optimieren komplexe Geschäftsprozesse — und digitalisieren sie als individuelle Software, interne Tools oder AI-gestützte Workflows.',
      audience: 'Für Operations-, Transformations- und Produktteams in wissensintensiven Organisationen und Vertical-SaaS-Unternehmen.',
      primary: 'Ablauf besprechen',
      secondary: 'Ausgewählte Arbeit',
    },
    thesis: {
      label: 'Unsere Perspektive',
      title: 'Gute Prozessautomatisierung beginnt nicht mit Software.',
      body: 'Es beginnt damit, den bestehenden Ablauf zu verstehen und zu verbessern: Ausnahmen, Übergaben, stilles Fachwissen und die Entscheidungen, die beim Menschen bleiben müssen. Erst dann wird daraus ein digitales Werkzeug, das im Alltag trägt.',
      steps: [
        ['01', 'Verstehen', 'Den realen Ablauf, die Beteiligten, Systeme und Reibung sichtbar machen.'],
        ['02', 'Verbessern', 'Vereinfachen, was unnötig kompliziert ist, und erkennen, was sich wiederholen lässt.'],
        ['03', 'Digitalisieren', 'Den verbesserten Ablauf als internes Tool, AI-Workflow oder Produktfunktion bauen.'],
        ['04', 'Verankern', 'Das Werkzeug in Team, Systeme und tägliche Arbeit integrieren.'],
      ],
    },
    work: {
      label: 'Ausgewählte Arbeit',
      title: 'Abläufe, die zu funktionierenden Systemen wurden.',
      note: 'Die Beispiele entstanden in verantwortlichen Produkt-, Vertrags- und Beratungsrollen von Tobias Treppmann.',
      cases: [
        {
          number: '01',
          context: 'ChurchDesk · Vertical SaaS · Produkt & Design',
          title: 'Aus Telefonkoordination wurde eine Plattformfähigkeit.',
          body: 'Ein Bestattungsprozess zwischen Pfarrpersonen, Friedhöfen und Bestattungsinstituten wurde in den bestehenden Kalender und Formularbaukasten integriert — und dadurch für Räume, Taufen, Hochzeiten und weitere Buchungen wiederverwendbar.',
          metricA: '70%',
          metricALabel: 'weniger Koordinationszeit',
          metricB: '90%',
          metricBLabel: 'Annahmequote',
          image: '/images/work/churchdesk-booking.png',
          imageAlt: 'Visualisierung der ChurchDesk-Verfügbarkeitslogik von Kalendereingabe bis zu buchbaren Terminen',
          href: 'https://treppmann.design/case-studies/churchdesk-booking-system',
          link: 'Fallstudie ansehen',
        },
        {
          number: '02',
          context: 'Ninox · Unabhängige Beratung · AI Onboarding',
          title: 'Aus einer Prozessbeschreibung wurde eine editierbare Anwendung.',
          body: 'Das AI-Onboarding übersetzt die Beschreibung eines Geschäftsprozesses in ein Datenmodell und zeigt das Ergebnis direkt im echten Builder. Die AI beschleunigt den Start; der Mensch sieht und verändert jedes Feld.',
          metricA: 'Prompt',
          metricALabel: 'als Ausgangspunkt',
          metricB: 'Schema',
          metricBLabel: 'direkt editierbar',
          image: '/images/work/ninox-onboarding.png',
          imageAlt: 'Ninox-Anwendung mit Ticketdatenbank und editierbarem Datensatz',
          href: 'https://treppmann.design/case-studies/ninox-ai-onboarding',
          link: 'Fallstudie ansehen',
        },
        {
          number: '03',
          context: 'Bibel TV · Vertragsrolle · Design Infrastructure',
          title: 'Aus manueller Farbauswahl wurde ein steuerbares System.',
          body: 'Eine produktionsfähige Farb-Engine erzeugt barrierearme Themes aus tausenden Programmbildern. Das Color Lab macht Schwellenwerte und Markenentscheidungen für Design steuerbar, statt sie im Code zu verstecken.',
          metricA: '1×',
          metricALabel: 'konfigurieren',
          metricB: 'Katalog',
          metricBLabel: 'automatisch thematisiert',
          image: '/images/work/bibeltv-color-lab.png',
          imageAlt: 'Bibel TV Color Lab mit Konfiguration und Vorschau für helle und dunkle App-Themes',
          href: 'https://treppmann.design/case-studies/bibeltv-color-api',
          link: 'Fallstudie ansehen',
        },
      ],
      moreTitle: 'Weitere Workflow-Systeme',
      more: [
        ['Fundraising', 'Vergangene Spendenbriefe analysiert und daraus einen geführten, menschlich kontrollierten Multi-Channel-Workflow gebaut.'],
        ['Zuschauerservice', 'Ein Copilot erstellt Antworten aus dem Servicehandbuch; Prüfung, Bearbeitung und Versand bleiben beim Team.'],
        ['Video-Metadaten', 'Manuelles Logging in strukturierte AI-gestützte Erfassung übersetzt, ohne redaktionelles Urteil zu entfernen.'],
        ['Design-System-API', 'Wiederkehrende Entscheidungen und Plattform-Synchronisation als gemeinsames, maschinenlesbares System organisiert.'],
      ],
    },
    offer: {
      label: 'Leistungen',
      title: 'Prozesse verbessern. Abläufe digitalisieren. Passende Software bauen.',
      intro: 'Wir steigen dort ein, wo ein wichtiger Geschäftsprozess noch aus Tabellen, Copy-and-paste, Einzelwissen und ungeeigneter Standardsoftware besteht — oder wo vorhandene Systeme die reale Arbeit unnötig schwer machen.',
      items: [
        ['Prozessanalyse & Optimierung', 'Ablauf, Ausnahmen, Beteiligte, Systeme und Kosten der Reibung untersuchen. Unnötige Schritte entfernen und den wertvollsten Ansatzpunkt bestimmen.'],
        ['Prozessdigitalisierung & Automatisierung', 'Manuelle Schritte vereinfachen, Systeme verbinden und wiederholbare Arbeit verlässlich digital abbilden.'],
        ['Individualsoftware & interne Tools', 'Passende Oberflächen und Werkzeuge für Fachprozesse bauen, die Standardsoftware nur mit Umwegen oder gar nicht unterstützt.'],
        ['AI-gestützte Workflows', 'Kontext, Automatisierung, Freigaben und Kontrollpunkte so gestalten, dass AI nützt und Verantwortung sichtbar bleibt. Mit echten Daten und Schnittstellen erproben und umsetzen.'],
      ],
      fitTitle: 'Ein guter Auftrag für uns',
      fit: [
        'betrifft einen wichtigen, wiederkehrenden Prozess',
        'braucht Fachwissen oder menschliches Urteil',
        'passt nicht sauber in Standardsoftware',
        'soll als Werkzeug erlebbar werden, nicht als Strategiepapier enden',
      ],
    },
    about: {
      label: 'Das Studio',
      title: 'Prozessverständnis, Design und technische Umsetzung.',
      body: 'Treppmann Studio ist ein unabhängiges Studio für Prozessdigitalisierung und interne Tools von Tobias Treppmann in Berlin. Er verbindet Prozessanalyse, Produktstrategie, UX, Systemdesign und AI-gestützte Umsetzung — und hat komplexe Abläufe bei Datameer, Ninox, ChurchDesk und Bibel TV in nutzbare Systeme übersetzt sowie service-to-product Transformation bei Hypoport begleitet.',
      principles: [
        ['Ablauf vor Oberfläche', 'Erst die Arbeit verbessern, dann das passende Werkzeug bauen.'],
        ['Prototyp statt PowerPoint', 'Ein funktionierendes Modell schafft bessere Entscheidungen.'],
        ['Urteilskraft bleibt sichtbar', 'Automatisieren, was wiederholbar ist. Kontrolle dort lassen, wo sie zählt.'],
      ],
    },
    contact: {
      label: 'Kontakt',
      title: 'Welcher Prozess kostet Ihr Team jeden Tag unnötig Zeit?',
      body: 'Bringen Sie den Prozess mit, den alle kennen, aber kein Standardtool wirklich abbildet. Wir finden heraus, ob daraus ein besseres Werkzeug werden kann.',
      cta: 'hello@treppmann.design',
      subject: 'Workflow für Treppmann Studio',
      location: 'Berlin · arbeitet international',
    },
    footer: 'Treppmann Studio · Prozessdigitalisierung & interne Tools',
  },
  en: {
    locale: 'en',
    path: '/en/',
    switchPath: '/',
    switchLabel: 'DE',
    metaTitle: 'Business process automation & internal tools | Treppmann Studio',
    metaDescription: 'Process improvement, workflow automation and custom software for complex business operations. Internal tools and AI-assisted workflows from Berlin.',
    nav: { work: 'Work', offer: 'Offer', studio: 'Studio', contact: 'Contact' },
    hero: {
      kicker: 'Process improvement · automation · custom software',
      title: 'Complex workflows. Tools that fit.',
      intro: 'We analyse and improve complex business processes — digitising them as custom software, internal tools or AI-assisted workflows.',
      audience: 'For operations, transformation and product teams in knowledge-intensive organisations and vertical SaaS companies.',
      primary: 'Discuss a process',
      secondary: 'Selected work',
    },
    thesis: {
      label: 'Our perspective',
      title: 'Good process automation does not begin with software.',
      body: 'It begins by understanding and improving the existing workflow: exceptions, handovers, tacit expertise and the decisions that must remain human. Only then can it become a digital tool that holds up in daily use.',
      steps: [
        ['01', 'Understand', 'Make the real workflow, people, systems and friction visible.'],
        ['02', 'Improve', 'Remove avoidable complexity and find what can repeat.'],
        ['03', 'Digitise', 'Build the improved workflow as an internal tool, AI system or product capability.'],
        ['04', 'Embed', 'Integrate the tool into the team, its systems and everyday work.'],
      ],
    },
    work: {
      label: 'Selected work',
      title: 'Workflows turned into working systems.',
      note: 'This work was led by Tobias Treppmann across product, contract and independent consulting roles.',
      cases: [
        {
          number: '01',
          context: 'ChurchDesk · Vertical SaaS · Product & Design',
          title: 'Phone coordination became a platform capability.',
          body: 'A funeral workflow spanning pastors, cemeteries and funeral homes was integrated into the existing calendar and form builder — making the same foundation reusable for rooms, baptisms, weddings and other bookings.',
          metricA: '70%',
          metricALabel: 'less coordination time',
          metricB: '90%',
          metricBLabel: 'acceptance rate',
          image: '/images/work/churchdesk-booking.png',
          imageAlt: 'Diagram of the ChurchDesk availability logic from calendar input to bookable times',
          href: 'https://treppmann.design/case-studies/churchdesk-booking-system',
          link: 'View case study',
        },
        {
          number: '02',
          context: 'Ninox · Independent consulting · AI onboarding',
          title: 'A process description became an editable application.',
          body: 'The AI onboarding turns a description of a business process into a data model and renders it in the real builder. AI accelerates the start; a person can see and change every field.',
          metricA: 'Prompt',
          metricALabel: 'as the starting point',
          metricB: 'Schema',
          metricBLabel: 'directly editable',
          image: '/images/work/ninox-onboarding.png',
          imageAlt: 'Ninox application showing a ticket database and an editable record',
          href: 'https://treppmann.design/case-studies/ninox-ai-onboarding',
          link: 'View case study',
        },
        {
          number: '03',
          context: 'Bibel TV · Contract role · Design infrastructure',
          title: 'Manual colour selection became a controllable system.',
          body: 'A production colour engine creates accessible themes from thousands of programme images. The Color Lab keeps thresholds and brand decisions in design hands instead of hiding them in code.',
          metricA: '1×',
          metricALabel: 'configure',
          metricB: 'Catalog',
          metricBLabel: 'themed automatically',
          image: '/images/work/bibeltv-color-lab.png',
          imageAlt: 'Bibel TV Color Lab with controls and light and dark application previews',
          href: 'https://treppmann.design/case-studies/bibeltv-color-api',
          link: 'View case study',
        },
      ],
      moreTitle: 'More workflow systems',
      more: [
        ['Fundraising', 'Analysed past fundraising letters and turned the findings into a guided, human-controlled multi-channel workflow.'],
        ['Customer support', 'A copilot drafts answers from the service handbook; the team retains review, editing and send decisions.'],
        ['Video metadata', 'Turned manual logging into structured AI-assisted capture without removing editorial judgement.'],
        ['Design system API', 'Organised repeated decisions and cross-platform synchronisation as a shared, machine-readable system.'],
      ],
    },
    offer: {
      label: 'Services',
      title: 'Improve processes. Digitise workflows. Build the right software.',
      intro: 'We enter where an important business process still depends on spreadsheets, copy and paste, individual knowledge and standard software that never quite fits — or where existing systems make the real work unnecessarily difficult.',
      items: [
        ['Process analysis & improvement', 'Study the workflow, exceptions, people, systems and cost of friction. Remove unnecessary steps and identify the highest-value intervention.'],
        ['Process digitisation & automation', 'Simplify manual steps, connect systems and turn repeatable work into a reliable digital workflow.'],
        ['Custom software & internal tools', 'Build interfaces and tools for specialist work that standard software supports only awkwardly or not at all.'],
        ['AI-assisted workflows', 'Design context, automation, approvals and controls so AI is useful while responsibility remains visible. Test and implement with real data and interfaces.'],
      ],
      fitTitle: 'A good engagement for us',
      fit: [
        'centres on an important, recurring process',
        'depends on domain expertise or human judgement',
        'does not fit standard software cleanly',
        'needs to become a tangible tool rather than end as a strategy document',
      ],
    },
    about: {
      label: 'The studio',
      title: 'Process understanding, design and technical execution.',
      body: 'Treppmann Studio is an independent workflow digitisation and internal tools practice led by Tobias Treppmann in Berlin. He connects process analysis, product strategy, UX, systems design and AI-assisted implementation — turning complex work into usable systems at Datameer, Ninox, ChurchDesk and Bibel TV, with service-to-product transformation work at Hypoport.',
      principles: [
        ['Workflow before interface', 'Improve the work first, then build the right tool.'],
        ['Prototype before PowerPoint', 'A working model creates better decisions.'],
        ['Keep judgement visible', 'Automate what can repeat. Keep control where it matters.'],
      ],
    },
    contact: {
      label: 'Contact',
      title: 'Which process costs your team unnecessary time every day?',
      body: 'Bring the process everyone knows is painful but no standard tool properly supports. We will find out whether it can become a better tool.',
      cta: 'hello@treppmann.design',
      subject: 'Workflow for Treppmann Studio',
      location: 'Berlin · working internationally',
    },
    footer: 'Treppmann Studio · Workflow digitisation & internal tools',
  },
} as const;
