export type Locale = 'de' | 'en';

export const content = {
  de: {
    locale: 'de-DE',
    path: '/',
    switchPath: '/en/',
    switchLabel: 'EN',
    metaTitle: 'Geschäftsprozesse digitalisieren | Treppmann Studio',
    metaDescription: 'Prozessoptimierung, Prozessautomatisierung und individuelle Software für komplexe Geschäftsabläufe. Interne Tools und KI-gestützte Workflows aus Berlin.',
    nav: { work: 'Arbeit', offer: 'Angebot', studio: 'Studio', contact: 'Kontakt' },
    hero: {
      kicker: 'Prozessoptimierung · Automatisierung · Individualsoftware',
      title: 'Komplexe Abläufe. Werkzeuge, die passen.',
      intro: 'Wir analysieren und optimieren komplexe Geschäftsprozesse — und digitalisieren sie als individuelle Software, interne Tools oder KI-gestützte Workflows.',
      audience: 'Für Operations-, Transformations- und Produktteams in wissensintensiven Organisationen und Vertical-SaaS-Unternehmen.',
      primary: 'Ablauf besprechen',
      secondary: 'Ausgewählte Arbeit',
    },
    experience: {
      label: 'Ausgewählte Erfahrung',
      ariaLabel: 'Ausgewählte berufliche Erfahrung',
      brands: ['Software AG', 'Ninox', 'Bibel TV', 'ChurchDesk', 'Datameer', 'Hypoport'],
    },
    thesis: {
      label: 'Unsere Perspektive',
      title: 'Gute Prozessautomatisierung beginnt nicht mit Software.',
      body: 'Es beginnt damit, den bestehenden Ablauf zu verstehen und zu verbessern: Ausnahmen, Übergaben, stilles Fachwissen und die Entscheidungen, die beim Menschen bleiben müssen. Erst dann wird daraus ein digitales Werkzeug, das im Alltag trägt.',
      steps: [
        ['01', 'Verstehen', 'Den realen Ablauf, die Beteiligten, Systeme und Reibung sichtbar machen.'],
        ['02', 'Verbessern', 'Vereinfachen, was unnötig kompliziert ist, und erkennen, was sich wiederholen lässt.'],
        ['03', 'Digitalisieren', 'Den verbesserten Ablauf als internes Tool, KI-Workflow oder Produktfunktion bauen.'],
        ['04', 'Verankern', 'Das Werkzeug in Team, Systeme und tägliche Arbeit integrieren.'],
      ],
    },
    work: {
      label: 'Ausgewählte Arbeit',
      title: 'Abläufe, die zu funktionierenden Systemen wurden.',
      note: 'Die Beispiele entstanden in verantwortlichen Produkt-, Vertrags- und Beratungsrollen von Tobias Treppmann.',
      cases: [
        {
          number: '01',
          context: 'ChurchDesk · Vertical SaaS · Produkt & Design',
          title: 'Aus Telefonkoordination wurde eine Plattformfähigkeit.',
          body: 'Ein Bestattungsprozess zwischen Pfarrpersonen, Friedhöfen und Bestattungsinstituten wurde in den bestehenden Kalender und Formularbaukasten integriert — und dadurch für Räume, Taufen, Hochzeiten und weitere Buchungen wiederverwendbar.',
          metricA: '70%',
          metricALabel: 'weniger Koordinationszeit',
          metricB: '90%',
          metricBLabel: 'Annahmequote',
          image: '/images/work/churchdesk-booking.png',
          imageAlt: 'Visualisierung der ChurchDesk-Verfügbarkeitslogik von Kalendereingabe bis zu buchbaren Terminen',
          href: 'https://treppmann.design/case-studies/churchdesk-booking-system',
          link: 'Fallstudie ansehen',
        },
        {
          number: '02',
          context: 'Ninox · Unabhängige Beratung · KI-Onboarding',
          title: 'Aus einer Prozessbeschreibung wurde eine editierbare Anwendung.',
          body: 'Das KI-Onboarding übersetzt die Beschreibung eines Geschäftsprozesses in ein Datenmodell und zeigt das Ergebnis direkt im echten Builder. Die KI beschleunigt den Start; der Mensch sieht und verändert jedes Feld.',
          metricA: 'Prompt',
          metricALabel: 'als Ausgangspunkt',
          metricB: 'Schema',
          metricBLabel: 'direkt editierbar',
          image: '/images/work/ninox-onboarding.png',
          imageAlt: 'Ninox-Anwendung mit Ticketdatenbank und editierbarem Datensatz',
          href: 'https://treppmann.design/case-studies/ninox-ai-onboarding',
          link: 'Fallstudie ansehen',
        },
        {
          number: '03',
          context: 'Bibel TV · Vertragsrolle · Design Infrastructure',
          title: 'Aus manueller Farbauswahl wurde ein steuerbares System.',
          body: 'Eine produktionsfähige Farb-Engine erzeugt barrierearme Themes aus tausenden Programmbildern. Das Color Lab macht Schwellenwerte und Markenentscheidungen für Design steuerbar, statt sie im Code zu verstecken.',
          metricA: '1×',
          metricALabel: 'konfigurieren',
          metricB: 'Katalog',
          metricBLabel: 'automatisch thematisiert',
          image: '/images/work/bibeltv-color-lab.png',
          imageAlt: 'Bibel TV Color Lab mit Konfiguration und Vorschau für helle und dunkle App-Themes',
          href: 'https://treppmann.design/case-studies/bibeltv-color-api',
          link: 'Fallstudie ansehen',
        },
      ],
      moreTitle: 'Weitere Workflow-Systeme',
      more: [
        ['Fundraising', 'Vergangene Spendenbriefe analysiert und daraus einen geführten, menschlich kontrollierten Multi-Channel-Workflow gebaut.'],
        ['Zuschauerservice', 'Ein Copilot erstellt Antworten aus dem Servicehandbuch; Prüfung, Bearbeitung und Versand bleiben beim Team.'],
        ['Video-Metadaten', 'Manuelles Logging in strukturierte KI-gestützte Erfassung übersetzt, ohne redaktionelles Urteil zu entfernen.'],
        ['Design-System-API', 'Wiederkehrende Entscheidungen und Plattform-Synchronisation als gemeinsames, maschinenlesbares System organisiert.'],
      ],
    },
    offer: {
      label: 'Leistungen',
      title: 'Prozesse verbessern. Abläufe digitalisieren. Passende Software bauen.',
      intro: 'Wir steigen dort ein, wo ein wichtiger Geschäftsprozess noch aus Tabellen, Copy-and-paste, Einzelwissen und ungeeigneter Standardsoftware besteht — oder wo vorhandene Systeme die reale Arbeit unnötig schwer machen.',
      items: [
        ['Prozessanalyse & Optimierung', 'Ablauf, Ausnahmen, Beteiligte, Systeme und Kosten der Reibung untersuchen. Unnötige Schritte entfernen und den wertvollsten Ansatzpunkt bestimmen.'],
        ['Prozessdigitalisierung & Automatisierung', 'Manuelle Schritte vereinfachen, Systeme verbinden und wiederholbare Arbeit verlässlich digital abbilden.'],
        ['Individualsoftware & interne Tools', 'Passende Oberflächen und Werkzeuge für Fachprozesse bauen, die Standardsoftware nur mit Umwegen oder gar nicht unterstützt.'],
        ['KI-gestützte Workflows', 'Kontext, Automatisierung, Freigaben und Kontrollpunkte so gestalten, dass KI nützt und Verantwortung sichtbar bleibt. Mit echten Daten und Schnittstellen erproben und umsetzen.'],
      ],
      fitTitle: 'Ein guter Auftrag für uns',
      fit: [
        'betrifft einen wichtigen, wiederkehrenden Prozess',
        'braucht Fachwissen oder menschliches Urteil',
        'passt nicht sauber in Standardsoftware',
        'soll als Werkzeug erlebbar werden, nicht als Strategiepapier enden',
      ],
    },
    about: {
      label: 'Das Studio',
      title: 'Prozessverständnis, Design und technische Umsetzung.',
      body: 'Treppmann Studio ist ein unabhängiges Studio für Prozessdigitalisierung und interne Tools von Tobias Treppmann in Berlin. Er verbindet Prozessanalyse, Produktstrategie, UX, Systemdesign und KI-gestützte Umsetzung — und hat komplexe Abläufe bei Datameer, Ninox, ChurchDesk und Bibel TV in nutzbare Systeme übersetzt sowie Service-to-Product-Transformation bei Hypoport begleitet.',
      principles: [
        ['Ablauf vor Oberfläche', 'Erst die Arbeit verbessern, dann das passende Werkzeug bauen.'],
        ['Prototyp statt PowerPoint', 'Ein funktionierendes Modell schafft bessere Entscheidungen.'],
        ['Urteilskraft bleibt sichtbar', 'Automatisieren, was wiederholbar ist. Kontrolle dort lassen, wo sie zählt.'],
      ],
    },
    contact: {
      label: 'Kontakt',
      title: 'Welcher Prozess kostet Ihr Team jeden Tag unnötig Zeit?',
      body: 'Bringen Sie den Prozess mit, den alle kennen, aber kein Standardtool wirklich abbildet. Wir finden heraus, ob daraus ein besseres Werkzeug werden kann.',
      cta: 'hello@treppmann.design',
      subject: 'Workflow für Treppmann Studio',
      location: 'Berlin · arbeitet international',
    },
    footer: 'Treppmann Studio · Prozessdigitalisierung & interne Tools',
  },
  en: {
    locale: 'en',
    path: '/en/',
    switchPath: '/',
    switchLabel: 'DE',
    metaTitle: 'Custom internal tools & workflow automation | Treppmann Studio',
    metaDescription: 'We design and build custom internal tools, workflow automation, and AI-assisted systems for complex operations that off-the-shelf software cannot handle.',
    nav: { work: 'Work', offer: 'Services', studio: 'Studio', contact: 'Contact' },
    hero: {
      kicker: 'Custom internal tools · workflow automation · applied AI',
      title: 'Turn complex operations into tools that work.',
      intro: 'We design and build custom internal tools, workflow automation, and AI-assisted systems for specialized work that off-the-shelf software cannot handle.',
      audience: 'For operations, product, and transformation teams in knowledge-intensive organizations and vertical SaaS companies.',
      primary: 'Discuss your workflow',
      secondary: 'Selected work',
    },
    experience: {
      label: 'Selected experience',
      ariaLabel: 'Selected professional experience',
      brands: ['Software AG', 'Ninox', 'Bibel TV', 'ChurchDesk', 'Datameer', 'Hypoport'],
    },
    thesis: {
      label: 'How we work',
      title: 'Automate the repeatable. Keep judgment where it matters.',
      body: 'We start with the work itself: the handoffs, exceptions, tacit knowledge, and decisions that make standard software fail. Then we improve the process and build the software around it.',
      steps: [
        ['01', 'Understand', 'Map the real workflow, systems, edge cases, and ownership.'],
        ['02', 'Improve', 'Remove friction before automating it.'],
        ['03', 'Build', 'Create a working tool with real data and integrations.'],
        ['04', 'Embed', 'Fit it into daily operations, governance, and the product roadmap.'],
      ],
    },
    work: {
      label: 'Selected work',
      title: 'Evidence from complex, real-world operations.',
      note: 'This work was led by Tobias Treppmann across product, contract and independent consulting roles.',
      cases: [
        {
          number: '01',
          context: 'ChurchDesk · Vertical SaaS · Product & Design',
          title: 'Multi-party phone coordination became a reusable booking capability.',
          body: 'A funeral workflow spanning pastors, cemeteries and funeral homes was integrated into the existing calendar and form builder — making the same foundation reusable for rooms, baptisms, weddings and other bookings.',
          metricA: '70%',
          metricALabel: 'less coordination time',
          metricB: '90%',
          metricBLabel: 'acceptance rate',
          image: '/images/work/churchdesk-booking.png',
          imageAlt: 'Diagram of the ChurchDesk availability logic from calendar input to bookable times',
          href: 'https://treppmann.design/case-studies/churchdesk-booking-system',
          link: 'View case study',
        },
        {
          number: '02',
          context: 'Ninox · Independent consulting · AI onboarding',
          title: 'A process description became an editable business application.',
          body: 'The AI onboarding turns a description of a business process into a data model and renders it in the real builder. AI accelerates the start; a person can see and change every field.',
          metricA: 'Prompt',
          metricALabel: 'as the starting point',
          metricB: 'Schema',
          metricBLabel: 'directly editable',
          image: '/images/work/ninox-onboarding.png',
          imageAlt: 'Ninox application showing a ticket database and an editable record',
          href: 'https://treppmann.design/case-studies/ninox-ai-onboarding',
          link: 'View case study',
        },
        {
          number: '03',
          context: 'Bibel TV · Contract role · Design infrastructure',
          title: 'Manual color selection became a scalable design system.',
          body: 'A production color engine creates accessible themes from thousands of program images. The Color Lab keeps thresholds and brand decisions in design hands instead of hiding them in code.',
          metricA: '1×',
          metricALabel: 'configure',
          metricB: 'Catalog',
          metricBLabel: 'themed automatically',
          image: '/images/work/bibeltv-color-lab.png',
          imageAlt: 'Bibel TV Color Lab with controls and light and dark application previews',
          href: 'https://treppmann.design/case-studies/bibeltv-color-api',
          link: 'View case study',
        },
      ],
      moreTitle: 'More workflow systems',
      more: [
        ['Fundraising', 'Analyzed past fundraising letters and turned the findings into a guided, human-controlled multi-channel workflow.'],
        ['Customer support', 'A copilot drafts answers from the service handbook; the team retains review, editing and send decisions.'],
        ['Video metadata', 'Turned manual logging into structured AI-assisted capture without removing editorial judgment.'],
        ['Design system API', 'Organized repeated decisions and cross-platform synchronization as a shared, machine-readable system.'],
      ],
    },
    offer: {
      label: 'Services',
      title: 'From operational friction to working software.',
      intro: 'Bring us a process held together by spreadsheets, copy and paste, tacit knowledge, or software that never quite fits. We identify the highest-value intervention and build something the team can use.',
      items: [
        ['Workflow analysis & process improvement', 'Map the work, edge cases, people, systems, and cost of friction. Remove unnecessary steps and identify the highest-value intervention.'],
        ['Custom internal tools', 'Build focused software for specialized operations that off-the-shelf products support poorly or not at all.'],
        ['Workflow automation & integration', 'Connect systems and automate repeatable work while keeping exceptions, approvals, and ownership explicit.'],
        ['AI-assisted operations', 'Use AI where context and variability matter, with the right controls, human review, real data, and production interfaces.'],
      ],
      fitTitle: 'A good engagement for us',
      fit: [
        'centers on an important, recurring workflow',
        'depends on domain expertise or human judgment',
        'does not fit standard software cleanly',
        'needs a working tool and a measurable operational outcome',
      ],
    },
    about: {
      label: 'The studio',
      title: 'Senior product judgment. Hands-on delivery.',
      body: 'Treppmann Studio is Tobias Treppmann’s independent practice in Berlin. He combines process analysis, product strategy, UX, systems design, and AI-assisted development. His work has turned complex operations into usable systems at Datameer, Ninox, ChurchDesk, and Bibel TV, and supported service-to-product transformation at Hypoport.',
      principles: [
        ['Start with the work', 'Improve the process before choosing the technology.'],
        ['Working software before slideware', 'A functional model creates better decisions.'],
        ['Human judgment by design', 'Automate what can repeat. Keep control where it matters.'],
      ],
    },
    contact: {
      label: 'Contact',
      title: 'What process is costing your team time, clarity, or control?',
      body: 'Bring the workflow your team has learned to work around. We will determine whether it needs process change, automation, or a purpose-built tool.',
      cta: 'hello@treppmann.design',
      subject: 'Workflow for Treppmann Studio',
      location: 'Berlin · working internationally',
    },
    footer: 'Treppmann Studio · Custom internal tools & workflow automation',
  },
} as const;
