export type Locale = 'de' | 'en';

export const content = {
  de: {
    locale: 'de-DE',
    path: '/',
    switchPath: '/en/',
    switchLabel: 'EN',
    metaTitle: 'Treppmann Studio — Werkzeuge für komplexe Arbeit',
    metaDescription: 'Unabhängiges Produkt- und Designstudio für individuelle Workflows, AI-gestützte Werkzeuge und Vertical SaaS.',
    nav: { work: 'Arbeit', offer: 'Angebot', studio: 'Studio', contact: 'Kontakt' },
    hero: {
      kicker: 'Produktdesign für besondere Arbeit',
      title: 'Komplexe Arbeit. Klare Werkzeuge.',
      intro: 'Wir entwickeln digitale Werkzeuge für Abläufe, die zu fachlich, zu speziell oder zu menschlich für Standardsoftware sind.',
      audience: 'Für Produkt-, Operations- und Transformationsteams in wissensintensiven Organisationen und Vertical-SaaS-Unternehmen.',
      primary: 'Arbeitsablauf besprechen',
      secondary: 'Ausgewählte Arbeit',
    },
    thesis: {
      label: 'Unsere Perspektive',
      title: 'Die beste Automatisierung beginnt nicht mit Automatisierung.',
      body: 'Sie beginnt damit, die Arbeit wirklich zu verstehen: Ausnahmen, Übergaben, stilles Fachwissen und die Entscheidungen, die beim Menschen bleiben müssen. Erst dann entsteht ein Werkzeug, das im Alltag trägt.',
      steps: [
        ['01', 'Verstehen', 'Den realen Ablauf, die Beteiligten und die Reibung sichtbar machen.'],
        ['02', 'Verdichten', 'Erkennen, was wiederholbar ist und wo Urteilskraft zählt.'],
        ['03', 'Bauen', 'Produktmodell, Interaktion und funktionierenden Prototyp zusammenführen.'],
        ['04', 'Verankern', 'Das Werkzeug anschlussfähig für Team, Systeme und Weiterentwicklung machen.'],
      ],
    },
    work: {
      label: 'Ausgewählte Arbeit',
      title: 'Belegt in echten, anspruchsvollen Abläufen.',
      note: 'Die Beispiele entstanden in verantwortlichen Produkt-, Vertrags- und Beratungsrollen von Tobias Treppmann.',
      cases: [
        {
          number: '01',
          context: 'ChurchDesk · Vertical SaaS · Produkt & Design',
          title: 'Aus Telefonkoordination wurde eine Plattformfähigkeit.',
          body: 'Ein Bestattungsprozess zwischen Pfarrpersonen, Friedhöfen und Bestattungsinstituten wurde in den bestehenden Kalender und Formularbaukasten integriert — und dadurch für Räume, Taufen, Hochzeiten und weitere Buchungen wiederverwendbar.',
          metricA: '70%',
          metricALabel: 'weniger Koordinationszeit',
          metricB: '90%',
          metricBLabel: 'Annahmequote',
          image: '/images/work/churchdesk-booking.png',
          imageAlt: 'Visualisierung der ChurchDesk-Verfügbarkeitslogik von Kalendereingabe bis zu buchbaren Terminen',
          href: 'https://treppmann.design/case-studies/churchdesk-booking-system',
          link: 'Fallstudie ansehen',
        },
        {
          number: '02',
          context: 'Ninox · Unabhängige Beratung · AI Onboarding',
          title: 'Aus einer Prozessbeschreibung wurde eine editierbare Anwendung.',
          body: 'Das AI-Onboarding übersetzt die Beschreibung eines Geschäftsprozesses in ein Datenmodell und zeigt das Ergebnis direkt im echten Builder. Die AI beschleunigt den Start; der Mensch sieht und verändert jedes Feld.',
          metricA: 'Prompt',
          metricALabel: 'als Ausgangspunkt',
          metricB: 'Schema',
          metricBLabel: 'direkt editierbar',
          image: '/images/work/ninox-onboarding.png',
          imageAlt: 'Ninox-Anwendung mit Ticketdatenbank und editierbarem Datensatz',
          href: 'https://treppmann.design/case-studies/ninox-ai-onboarding',
          link: 'Fallstudie ansehen',
        },
        {
          number: '03',
          context: 'Bibel TV · Vertragsrolle · Design Infrastructure',
          title: 'Aus manueller Farbauswahl wurde ein steuerbares System.',
          body: 'Eine produktionsfähige Farb-Engine erzeugt barrierearme Themes aus tausenden Programmbildern. Das Color Lab macht Schwellenwerte und Markenentscheidungen für Design steuerbar, statt sie im Code zu verstecken.',
          metricA: '1×',
          metricALabel: 'konfigurieren',
          metricB: 'Katalog',
          metricBLabel: 'automatisch thematisiert',
          image: '/images/work/bibeltv-color-lab.png',
          imageAlt: 'Bibel TV Color Lab mit Konfiguration und Vorschau für helle und dunkle App-Themes',
          href: 'https://treppmann.design/case-studies/bibeltv-color-api',
          link: 'Fallstudie ansehen',
        },
      ],
      moreTitle: 'Weitere Workflow-Systeme',
      more: [
        ['Fundraising', 'Vergangene Spendenbriefe analysiert und daraus einen geführten, menschlich kontrollierten Multi-Channel-Workflow gebaut.'],
        ['Zuschauerservice', 'Ein Copilot erstellt Antworten aus dem Servicehandbuch; Prüfung, Bearbeitung und Versand bleiben beim Team.'],
        ['Video-Metadaten', 'Manuelles Logging in strukturierte AI-gestützte Erfassung übersetzt, ohne redaktionelles Urteil zu entfernen.'],
        ['Design-System-API', 'Wiederkehrende Entscheidungen und Plattform-Synchronisation als gemeinsames, maschinenlesbares System organisiert.'],
      ],
    },
    offer: {
      label: 'Angebot',
      title: 'Von der Reibung zum funktionierenden Werkzeug.',
      intro: 'Wir steigen dort ein, wo ein wichtiger Ablauf noch aus Tabellen, Copy-and-paste, Einzelwissen und ungeeigneter Standardsoftware besteht.',
      items: [
        ['Workflow Discovery', 'Ablauf, Ausnahmen, Beteiligte und Kosten der Reibung untersuchen. Den wertvollsten Ansatzpunkt bestimmen.'],
        ['Product & Interaction Design', 'Den Workflow als klares Produktmodell, Interface und durchgängige Nutzungserfahrung entwerfen.'],
        ['AI-assisted Tools', 'Kontext, Prompts, Freigaben und Kontrollpunkte so gestalten, dass AI nützt und Verantwortung sichtbar bleibt.'],
        ['Working Prototypes', 'Mit echten Daten und realen Schnittstellen bauen, damit Teams nicht über Folien, sondern über ein funktionierendes System entscheiden.'],
      ],
      fitTitle: 'Ein guter Auftrag für uns',
      fit: [
        'betrifft einen wichtigen, wiederkehrenden Ablauf',
        'braucht Fachwissen oder menschliches Urteil',
        'passt nicht sauber in Standardsoftware',
        'soll als Werkzeug erlebbar werden, nicht als Strategiepapier enden',
      ],
    },
    about: {
      label: 'Das Studio',
      title: 'Strategisches Produktdenken, nah an der Umsetzung.',
      body: 'Treppmann Studio ist ein unabhängiges Produkt- und Designstudio von Tobias Treppmann in Berlin. Er verbindet Produktstrategie, Research, UX, Systemdesign und AI-gestütztes Prototyping — und hat Design- und Produktarbeit bei Datameer, Ninox, ChurchDesk und Bibel TV verantwortet sowie service-to-product Transformation bei Hypoport begleitet.',
      principles: [
        ['Domänenwissen vor Features', 'Das Werkzeug folgt der Arbeit — nicht umgekehrt.'],
        ['Prototyp statt PowerPoint', 'Ein funktionierendes Modell schafft bessere Entscheidungen.'],
        ['Urteilskraft bleibt sichtbar', 'Automatisieren, was wiederholbar ist. Kontrolle dort lassen, wo sie zählt.'],
      ],
    },
    contact: {
      label: 'Kontakt',
      title: 'Welcher Ablauf kostet Ihr Team jeden Tag unnötig Zeit?',
      body: 'Bringen Sie den Prozess mit, den alle kennen, aber kein Standardtool wirklich abbildet. Wir finden heraus, ob daraus ein besseres Werkzeug werden kann.',
      cta: 'hello@treppmann.design',
      subject: 'Workflow für Treppmann Studio',
      location: 'Berlin · arbeitet international',
    },
    footer: 'Treppmann Studio · Independent product and design practice',
  },
  en: {
    locale: 'en',
    path: '/en/',
    switchPath: '/',
    switchLabel: 'DE',
    metaTitle: 'Treppmann Studio — Tools for complex work',
    metaDescription: 'Independent product and design studio for custom workflows, AI-assisted tools and vertical SaaS.',
    nav: { work: 'Work', offer: 'Offer', studio: 'Studio', contact: 'Contact' },
    hero: {
      kicker: 'Product design for particular work',
      title: 'Complex work. Clear tools.',
      intro: 'We design digital tools for work that is too specialised, too specific or too human for standard software.',
      audience: 'For product, operations and transformation teams in knowledge-intensive organisations and vertical SaaS companies.',
      primary: 'Discuss a workflow',
      secondary: 'Selected work',
    },
    thesis: {
      label: 'Our perspective',
      title: 'The best automation does not begin with automation.',
      body: 'It begins by understanding the work: exceptions, handovers, tacit expertise and the decisions that must remain human. Only then can a tool hold up in day-to-day use.',
      steps: [
        ['01', 'Understand', 'Make the real workflow, people and friction visible.'],
        ['02', 'Distil', 'Find what can repeat and where judgement matters.'],
        ['03', 'Build', 'Bring the product model, interaction and working prototype together.'],
        ['04', 'Embed', 'Make the tool viable for the team, its systems and further development.'],
      ],
    },
    work: {
      label: 'Selected work',
      title: 'Proven in demanding, real-world workflows.',
      note: 'This work was led by Tobias Treppmann across product, contract and independent consulting roles.',
      cases: [
        {
          number: '01',
          context: 'ChurchDesk · Vertical SaaS · Product & Design',
          title: 'Phone coordination became a platform capability.',
          body: 'A funeral workflow spanning pastors, cemeteries and funeral homes was integrated into the existing calendar and form builder — making the same foundation reusable for rooms, baptisms, weddings and other bookings.',
          metricA: '70%',
          metricALabel: 'less coordination time',
          metricB: '90%',
          metricBLabel: 'acceptance rate',
          image: '/images/work/churchdesk-booking.png',
          imageAlt: 'Diagram of the ChurchDesk availability logic from calendar input to bookable times',
          href: 'https://treppmann.design/case-studies/churchdesk-booking-system',
          link: 'View case study',
        },
        {
          number: '02',
          context: 'Ninox · Independent consulting · AI onboarding',
          title: 'A process description became an editable application.',
          body: 'The AI onboarding turns a description of a business process into a data model and renders it in the real builder. AI accelerates the start; a person can see and change every field.',
          metricA: 'Prompt',
          metricALabel: 'as the starting point',
          metricB: 'Schema',
          metricBLabel: 'directly editable',
          image: '/images/work/ninox-onboarding.png',
          imageAlt: 'Ninox application showing a ticket database and an editable record',
          href: 'https://treppmann.design/case-studies/ninox-ai-onboarding',
          link: 'View case study',
        },
        {
          number: '03',
          context: 'Bibel TV · Contract role · Design infrastructure',
          title: 'Manual colour selection became a controllable system.',
          body: 'A production colour engine creates accessible themes from thousands of programme images. The Color Lab keeps thresholds and brand decisions in design hands instead of hiding them in code.',
          metricA: '1×',
          metricALabel: 'configure',
          metricB: 'Catalog',
          metricBLabel: 'themed automatically',
          image: '/images/work/bibeltv-color-lab.png',
          imageAlt: 'Bibel TV Color Lab with controls and light and dark application previews',
          href: 'https://treppmann.design/case-studies/bibeltv-color-api',
          link: 'View case study',
        },
      ],
      moreTitle: 'More workflow systems',
      more: [
        ['Fundraising', 'Analysed past fundraising letters and turned the findings into a guided, human-controlled multi-channel workflow.'],
        ['Customer support', 'A copilot drafts answers from the service handbook; the team retains review, editing and send decisions.'],
        ['Video metadata', 'Turned manual logging into structured AI-assisted capture without removing editorial judgement.'],
        ['Design system API', 'Organised repeated decisions and cross-platform synchronisation as a shared, machine-readable system.'],
      ],
    },
    offer: {
      label: 'Offer',
      title: 'From operational friction to a working tool.',
      intro: 'We enter where an important workflow still depends on spreadsheets, copy and paste, individual knowledge and standard software that never quite fits.',
      items: [
        ['Workflow discovery', 'Study the workflow, exceptions, participants and cost of friction. Identify the highest-value point of intervention.'],
        ['Product & interaction design', 'Shape the workflow into a clear product model, interface and end-to-end experience.'],
        ['AI-assisted tools', 'Design context, prompts, approvals and controls so AI is useful while responsibility remains visible.'],
        ['Working prototypes', 'Build with real data and real interfaces so teams can decide from a working system rather than a slide deck.'],
      ],
      fitTitle: 'A good engagement for us',
      fit: [
        'centres on an important, recurring workflow',
        'depends on domain expertise or human judgement',
        'does not fit standard software cleanly',
        'needs to become a tangible tool rather than end as a strategy document',
      ],
    },
    about: {
      label: 'The studio',
      title: 'Strategic product thinking, close to implementation.',
      body: 'Treppmann Studio is an independent product and design practice led by Tobias Treppmann in Berlin. He connects product strategy, research, UX, systems design and AI-assisted prototyping — with product and design leadership experience at Datameer, Ninox, ChurchDesk and Bibel TV, plus service-to-product transformation work at Hypoport.',
      principles: [
        ['Domain knowledge before features', 'The tool follows the work, not the other way around.'],
        ['Prototype before PowerPoint', 'A working model creates better decisions.'],
        ['Keep judgement visible', 'Automate what can repeat. Keep control where it matters.'],
      ],
    },
    contact: {
      label: 'Contact',
      title: 'Which workflow costs your team unnecessary time every day?',
      body: 'Bring the process everyone knows is painful but no standard tool properly supports. We will find out whether it can become a better tool.',
      cta: 'hello@treppmann.design',
      subject: 'Workflow for Treppmann Studio',
      location: 'Berlin · working internationally',
    },
    footer: 'Treppmann Studio · Independent product and design practice',
  },
} as const;
